parameters:
#    voy_php_fig.example.class: Voy\PhpFigBundle\Example

services:
#    voy_php_fig.example:
#        class: %voy_php_fig.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
